services:
    nginx:
        image: nginx:1.23.1-alpine
        ports:
            - '443:443'
        volumes:
            - './public:/var/www/html:ro'
            - './docker/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './docker/certs:/etc/ssl/certs:ro'

    node:
        command: scripts/watch.js
        image: node:18.6.0-alpine3.16
        user: ${HOST_UID:?}
        volumes:
            - '.:/home/node/app'
        working_dir: /home/node/app
