services:
    caddy:
        image: caddy:2.6.2-alpine
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        volumes:
            - ./docker/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./docker/certs:/etc/ssl/certs/public:ro
            - ./public:/srv:ro

    node:
        command: scripts/watch.js
        image: node:19.0.0-alpine3.16
        init: true
        user: ${HOST_UID:?}
        volumes:
            - .:/home/node/app
        working_dir: /home/node/app
