version: "3"
services:
    nginx:
        build: docker/nginx
        ports:
            - '${NGINX_PORT:-8080}:443'
        volumes:
            - './public:/var/www/html:ro'
            - './nginx.conf:/etc/nginx/nginx.conf:ro'

    node:
        image: node:13.1.0-alpine
        volumes:
            - '.:/home/node/app'
        working_dir: /home/node/app
