version: "3"
services:
    nginx:
        image: nginx:1.21.6-alpine
        ports:
            - '443:443'
        volumes:
            - './public:/var/www/html:ro'
            - './docker/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './docker/certs:/etc/ssl/certs:ro'

    node:
        image: node:17.8.0-alpine3.15
        command: node scripts/watch.js
        volumes:
            - '.:/home/node/app'
        working_dir: /home/node/app
