version: "3"
services:
    nginx:
        image: nginx:1.17.6-alpine
        ports:
            - '${NGINX_PORT:-8080}:443'
        volumes:
            - './public:/var/www/html:ro'
            - './docker/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './docker/certs:/etc/ssl/certs:ro'

    node:
        image: node:13.2.0-alpine3.10
        command: node docker/watch.js
        volumes:
            - '.:/home/node/app'
        working_dir: /home/node/app
