version: "3"
services:
    nginx:
        image: nginx:1.20.0-alpine
        ports:
            - '443:443'
        volumes:
            - './public:/var/www/html:ro'
            - './docker/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './docker/certs:/etc/ssl/certs:ro'

    node:
        image: node:16.1.0-alpine3.13
        command: node docker/watch.js
        volumes:
            - '.:/home/node/app'
        working_dir: /home/node/app
