name: publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: '18.7.0'

      - name: install dependencies
        run: npm ci --no-audit --prefer-offline

      - name: compile
        run: node scripts/compile.js

      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/deploy-pages@v1

