name: publish
on:
  push:
    branches:
      - master
    paths:
      - source/**
      - package-lock.json
      - scripts/compile.js
      - scripts/tokenizer.js
      - scripts/grammar/*
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: '17.9.0'
      - name: install dependencies
        run: npm ci --no-audit --prefer-offline
      - name: build
        run: node scripts/compile.js
      - name: deploy
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: public
          commit-message: publish ${{ github.sha }}
