name: publish
on:
  push:
    branches:
      - master
    paths:
      - source/**
      - package-lock.json
      - compile.js
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - name: install dependencies
        run: npm ci
      - name: build
        run: node compile.js
      - name: deploy
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: public
          commit-message: publish ${{ github.sha }}
